EE3371/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<ec>', views.index, name='index'),
    path('record/', views.record, name='record'),
]

polls/models.py
from django.db import models

import datetime

from django.db import models
from django.utils import timezone

class Category(models.Model):
    text = models.CharField(max_length = 100)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.text

class Description(models.Model):
    category = models.ForeignKey('Category', on_delete=models.CASCADE, blank = True)
    text = models.CharField(max_length=10000)
    timestamp = models.DateTimeField(default = datetime.datetime.now())

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Description, Category


def index(request, ec = ''):
    categories = Category.objects.all()
    context = {'categories' : categories, 'ec' : ec}
    return render(request, 'polls/index.html', context)

def record(request):
    context = {}
    text = request.POST['Description']
    try:
        pk = request.POST['choice']
    except KeyError:
        return redirect('polls:index', ec = 'caterr')
    c = Category.objects.get(pk = pk)
    c.votes += 1
    c.save()
    d = Description(text = text, category = c)
    d.save()


    context['categories'] = Category.objects.all()

    return render(request, 'polls/submitted.html', context)

polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<h1>Welcome to the Micro 1 Lab Feedback Site!</h1><br>

{% if ec %}
    <h3> PLEASE SELECT A CATEGORY! </h3>
{% endif %}

<h3>
Pick a category that you are struggling with and provide a short text description. <br>
This information is anonymous and will help us decide what we cover in the short lab workshops! <br>
We appreciate your time and feedback. <br>
</h3>
<form action="{% url 'polls:record' %}" method="post">
{% csrf_token %}
{% for choice in categories %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.text }}</label><br>
{% endfor %}
<textarea name="Description" class="txt" rows="20" cols="100">
</textarea>
<br>
<br>
<input type="submit" value="Go">
</form>

polls/templates/polls/submitted.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<h1>Your form has been submitted, thank you!</h1><br>

{% for item in categories %}
    <h2> {{item.text}} - {{item.votes}} </h2><br>
{% endfor %}